"""Noop squash placeholder (no schema changes)

Revision ID: 5a350af36181
Revises: d1080d27637f
Create Date: 2026-09-28 12:29:54.845506

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "5a350af36181"
down_revision: str | Sequence[str] | None = "d1080d27637f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
